# Generated by Django 4.2 on 2023-05-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sity_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.sity')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tarif')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.client')),
            ],
        ),
        migrations.AddField(
            model_name='tarif',
            name='tarifs',
            field=models.ManyToManyField(through='mainapp.Operator', to='mainapp.tarifs'),
        ),
        migrations.AddField(
            model_name='tarifs',
            name='users',
            field=models.ManyToManyField(through='mainapp.Operator', to='mainapp.tarifs'),
        ),
    ]
